language: java
jdk:
  -openjdk11
branches:
  only:
      - master

before_install:
  - chmod +x gradlew

  #Travis CI 서버의 Home
cache:
    directories:
        - '$HOME/.m2/repository'
        - '$HOME/.gradle'

# main 브랜치에 push 되면 수행되는 명령어
script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh bofore-deploy/
  - cp appsepc.yml before-deploy/
  - cp build/libs/*jar before-deploy/
  - cd before-deploy && zip -r before-deploy
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/awsbook.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: awsbook-mino
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-untill-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: awsbook-mino
    key: awsBOOK.zip
    bundly-type: zip
    application: awsbook
    deployment_group: awsbook-group
    region: ap-northeast-2
    wait-until-deployed: true


#CI 실행 완료 시 메일로 알람
notifications:
    email:
        recipients:
          -qawsedrfnnn@gmail.com